#!/usr/bin/env node

/**
 * This script parses index.html and sets the version query string of each
 * resource to be the MD5 hash of that resource.
 */

const fs = require('fs');
const crypto = require('crypto');
const child_process = require('child_process');
const Config = require('./config/config');

process.chdir(__dirname);

if (process.argv[2] === 'full') {
	child_process.execSync('node ../client/build-tools/build-indexes', {stdio: 'inherit'});
}

function updateFiles() {
	let indexContents = fs.readFileSync('index.template.php', {encoding: 'utf8'});

	// add hashes to js and css files
	process.stdout.write("Updating hashes... ");
	indexContents = indexContents.replace(/(src|href)="\/(.*?)\?[a-z0-9]*?"/g, function (a, b, c) {
		let hash = Math.random(); // just in case creating the hash fails
		try {
			var filepath = c;
			if (c.includes('/play.pokemonshowdown.com/')) {
				const filename = c.replace('/play.pokemonshowdown.com/', '');
				filepath = '../play.pokemonshowdown.com/' + filename;
			}
			const fstr = fs.readFileSync(filepath, {encoding: 'utf8'});
			hash = crypto.createHash('md5').update(fstr).digest('hex').substr(0, 8);
		} catch (e) {}

		return b + '="/' + c + '?' + hash + '"';
	});
	indexContents = indexContents.replace(/(src|href)="(.*?)\/(.*?)[a-z0-9]*?"/g, (match) => replaceRoutes(match));
	console.log("DONE");

	process.stdout.write("Writing new `index.php` file... ");
	fs.writeFileSync('index.php', indexContents);
	console.log("DONE");
}

function replaceRoutes(url) {
	return url.replace('/replay.pokemonshowdown.com/', '/' + Config.routes.replays + '/')
		.replace('/play.pokemonshowdown.com/', '/' + Config.routes.client + '/')
		.replace('/pokemonshowdown.com/', '/' + Config.routes.root + '/');
}

updateFiles();

child_process.execSync('node ./cms/build', {stdio: 'inherit'});

// process.stdout.write("Preparing ek folder...");
// fs.cpSync("articles", "ek/articles", { recursive: true });
// fs.cpSync("config", "ek/config", { recursive: true });
// fs.cpSync("images", "ek/images", { recursive: true });
// fs.cpSync("js", "ek/js", { recursive: true });
// fs.cpSync("theme", "ek/theme", { recursive: true });
// fs.cpSync("favicon.ico", "ek/favicon.ico");
// fs.cpSync("index.php", "ek/index.php");
// 
// fs.cpSync("sprites", "ek/sprites", { recursive: true });
// 
// fs.cpSync("../client/play.pokemonshowdown.com/style", "ek/play.pokemonshowdown.com/style", { recursive: true });
// fs.cpSync("../client/play.pokemonshowdown.com/config", "ek/play.pokemonshowdown.com/config", { recursive: true });
// fs.cpSync("../client/play.pokemonshowdown.com/data", "ek/play.pokemonshowdown.com/data", { recursive: true });
// fs.cpSync("../client/play.pokemonshowdown.com/js", "ek/play.pokemonshowdown.com/js", { recursive: true });

// console.log("DONE!")